name: Bellbellplugin
version: 0.1.2
main: com.insanephin.Bellbellplugin.Bellbellplugin

commands:
  tools:
    description: Add iron set in your inventory
    usage: /t, /tools, /ㅌ
    aliases: [t, ㅌ]

  spawn:
    description: Teleport your bed location
    usage: /spawn, /넴주, /sp
    aliases: [넴주, sp]

  back:
    description: Teleport before death
    usage: b, back
    aliases: [b]
